In [ ]:
import numpy as np

# zatím vytvářím pouze jednoduché šablony pro testování
# (bez falešných cest, bez přerušení atd.)

# n - velikost matice (n x n)
def create_simple_tem(n):
    template = np.ones((n, n), dtype=int)

    mid = n // 2  # prostřední řádek

    for i in range(mid + 1):
        template[i, 0] = 0  # cesta dolů doprostřed v levém sloupci

    for j in range(n):
        template[mid, j] = 0  # cesta doprava

    for i in range(mid + 1, n):
        template[i, n - 1] = 0 # cesta dolů v pravém sloupci

    return template


# z - velikost "zigzag" úseček
def create_zigzag_tem(n, z):
    template = np.ones((n, n), dtype=int)

    i = 0
    j = 0

    # hlavní zigzag část
    while i + z < n and j + z < n:
        # svislý úsek dolů
        for k in range(z):
            template[i + k, j] = 0
        i += z - 1  # končíme dole

        # vodorovně doprava
        for l in range(1, z):
            template[i, j + l] = 0
        j += z - 1  # končíme vpravo

        # příprava na další "zig zag"
        
    template[i, j] = 0
    
    # dokončení do pravého dolního rohu
    while (i, j) != (n - 1, n - 1):
        
        if i < n - 1:
            i += 1
        template[i, j] = 0
        if j < n - 1:
            j += 1
        template[i, j] = 0
            
    return template


# f - fraction - určuje, do jakého zlomu bude matice rozdělena
def create_best_tem(n, f):
    template = np.ones((n, n), dtype=int)

    mid = n // 2
    fraction = n // f

    # 1. Dolů po levém okraji
    for i in range(mid + 1):
        template[i, 0] = 0

    # 2. Doprava ve středu
    for j in range(mid + 1):
        template[mid, j] = 0

    # 3. Nahoru do zlomu ve sloupci mid
    for i in range(mid - 1, fraction - 1, -1):
        template[i, mid] = 0

    # 4. Doprava z mid na n - fraction v řádku fraction
    for j in range(mid + 1, n - fraction):
        template[fraction, j] = 0

    # 5. Dolů vpravo – sloupec n - fraction
    for i in range(fraction + 1, n - fraction):
        template[i, n - fraction - 1] = 0

    # 6. Doleva – v řádku n - fraction
    for j in range(n - fraction - 2, mid - 1, -1):
        template[n - fraction - 1, j] = 0

    # 7. Dolů středem ke spodnímu řádku
    for i in range(n - fraction, n):
        template[i, mid] = 0

    # 8. Doprava do pravého dolního rohu
    for j in range(mid + 1, n):
        template[n - 1, j] = 0

    return template

print(create_simple_tem(11))
print(create_zigzag_tem(13, 3))
print(create_best_tem(11, 3))

[[0 1 1 1 1 1 1 1 1 1 1 1 1]
 [0 1 1 1 1 1 1 1 1 1 1 1 1]
 [0 0 0 1 1 1 1 1 1 1 1 1 1]
 [1 1 0 1 1 1 1 1 1 1 1 1 1]
 [1 1 0 0 0 1 1 1 1 1 1 1 1]
 [1 1 1 1 0 1 1 1 1 1 1 1 1]
 [1 1 1 1 0 0 0 1 1 1 1 1 1]
 [1 1 1 1 1 1 0 1 1 1 1 1 1]
 [1 1 1 1 1 1 0 0 0 1 1 1 1]
 [1 1 1 1 1 1 1 1 0 1 1 1 1]
 [1 1 1 1 1 1 1 1 0 0 0 1 1]
 [1 1 1 1 1 1 1 1 1 1 0 0 1]
 [1 1 1 1 1 1 1 1 1 1 1 0 0]]
[[0 1 1 1 1 1 1 1 1 1 1]
 [0 1 1 1 1 1 1 1 1 1 1]
 [0 1 1 1 1 1 1 1 1 1 1]
 [0 1 1 1 1 0 0 0 1 1 1]
 [0 1 1 1 1 0 1 0 1 1 1]
 [0 0 0 0 0 0 1 0 1 1 1]
 [1 1 1 1 1 1 1 0 1 1 1]
 [1 1 1 1 1 0 0 0 1 1 1]
 [1 1 1 1 1 0 1 1 1 1 1]
 [1 1 1 1 1 0 1 1 1 1 1]
 [1 1 1 1 1 0 0 0 0 0 0]]
